//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bloomberg {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockQuote", Namespace="http://www.restfulwebservices.net/DataContracts/2008/01")]
    [System.SerializableAttribute()]
    public partial class StockQuote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HighField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MktCapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviousCloseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PercentageChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnnRangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EarnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElapsedMillisecondsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Last {
            get {
                return this.LastField;
            }
            set {
                if ((object.ReferenceEquals(this.LastField, value) != true)) {
                    this.LastField = value;
                    this.RaisePropertyChanged("Last");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Change {
            get {
                return this.ChangeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeField, value) != true)) {
                    this.ChangeField = value;
                    this.RaisePropertyChanged("Change");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Open {
            get {
                return this.OpenField;
            }
            set {
                if ((object.ReferenceEquals(this.OpenField, value) != true)) {
                    this.OpenField = value;
                    this.RaisePropertyChanged("Open");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string High {
            get {
                return this.HighField;
            }
            set {
                if ((object.ReferenceEquals(this.HighField, value) != true)) {
                    this.HighField = value;
                    this.RaisePropertyChanged("High");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Low {
            get {
                return this.LowField;
            }
            set {
                if ((object.ReferenceEquals(this.LowField, value) != true)) {
                    this.LowField = value;
                    this.RaisePropertyChanged("Low");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((object.ReferenceEquals(this.VolumeField, value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string MktCap {
            get {
                return this.MktCapField;
            }
            set {
                if ((object.ReferenceEquals(this.MktCapField, value) != true)) {
                    this.MktCapField = value;
                    this.RaisePropertyChanged("MktCap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string PreviousClose {
            get {
                return this.PreviousCloseField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviousCloseField, value) != true)) {
                    this.PreviousCloseField = value;
                    this.RaisePropertyChanged("PreviousClose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string PercentageChange {
            get {
                return this.PercentageChangeField;
            }
            set {
                if ((object.ReferenceEquals(this.PercentageChangeField, value) != true)) {
                    this.PercentageChangeField = value;
                    this.RaisePropertyChanged("PercentageChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string AnnRange {
            get {
                return this.AnnRangeField;
            }
            set {
                if ((object.ReferenceEquals(this.AnnRangeField, value) != true)) {
                    this.AnnRangeField = value;
                    this.RaisePropertyChanged("AnnRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string Earns {
            get {
                return this.EarnsField;
            }
            set {
                if ((object.ReferenceEquals(this.EarnsField, value) != true)) {
                    this.EarnsField = value;
                    this.RaisePropertyChanged("Earns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string PE {
            get {
                return this.PEField;
            }
            set {
                if ((object.ReferenceEquals(this.PEField, value) != true)) {
                    this.PEField = value;
                    this.RaisePropertyChanged("PE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string ElapsedMilliseconds {
            get {
                return this.ElapsedMillisecondsField;
            }
            set {
                if ((object.ReferenceEquals(this.ElapsedMillisecondsField, value) != true)) {
                    this.ElapsedMillisecondsField = value;
                    this.RaisePropertyChanged("ElapsedMilliseconds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DefaultFaultContract", Namespace="http://GOTLServices.FaultContracts/2008/01")]
    [System.SerializableAttribute()]
    public partial class DefaultFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorIdField;
        
        private string ErrorMessageField;
        
        private System.Guid CorrelationIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorId {
            get {
                return this.ErrorIdField;
            }
            set {
                if ((this.ErrorIdField.Equals(value) != true)) {
                    this.ErrorIdField = value;
                    this.RaisePropertyChanged("ErrorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Guid CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                if ((this.CorrelationIdField.Equals(value) != true)) {
                    this.CorrelationIdField = value;
                    this.RaisePropertyChanged("CorrelationId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.restfulwebservices.net/ServiceContracts/2008/01", ConfigurationName="Bloomberg.IStockQuoteService")]
    public interface IStockQuoteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="GetStockQuote", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/IStockQuoteService/Get" +
            "StockQuoteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Bloomberg.DefaultFaultContract), Action="http://www.restfulwebservices.net/ServiceContracts/2008/01/IStockQuoteService/Get" +
            "StockQuoteDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://GOTLServices.FaultContracts/2008/01")]
        Bloomberg.StockQuote GetStockQuote(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetStockQuote", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/IStockQuoteService/Get" +
            "StockQuoteResponse")]
        System.Threading.Tasks.Task<Bloomberg.StockQuote> GetStockQuoteAsync(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetWorldMajorIndices", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/IStockQuoteService/Get" +
            "WorldMajorIndicesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Bloomberg.DefaultFaultContract), Action="http://www.restfulwebservices.net/ServiceContracts/2008/01/IStockQuoteService/Get" +
            "WorldMajorIndicesDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://GOTLServices.FaultContracts/2008/01")]
        System.Collections.Generic.List<Bloomberg.StockQuote> GetWorldMajorIndices();
        
        [System.ServiceModel.OperationContractAttribute(Action="GetWorldMajorIndices", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/IStockQuoteService/Get" +
            "WorldMajorIndicesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Bloomberg.StockQuote>> GetWorldMajorIndicesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockQuoteServiceChannel : Bloomberg.IStockQuoteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockQuoteServiceClient : System.ServiceModel.ClientBase<Bloomberg.IStockQuoteService>, Bloomberg.IStockQuoteService {
        
        public StockQuoteServiceClient() {
        }
        
        public StockQuoteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockQuoteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockQuoteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockQuoteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Bloomberg.StockQuote GetStockQuote(string request) {
            return base.Channel.GetStockQuote(request);
        }
        
        public System.Threading.Tasks.Task<Bloomberg.StockQuote> GetStockQuoteAsync(string request) {
            return base.Channel.GetStockQuoteAsync(request);
        }
        
        public System.Collections.Generic.List<Bloomberg.StockQuote> GetWorldMajorIndices() {
            return base.Channel.GetWorldMajorIndices();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Bloomberg.StockQuote>> GetWorldMajorIndicesAsync() {
            return base.Channel.GetWorldMajorIndicesAsync();
        }
    }
}
