// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
/*
namespace StockQuote.Bloomberg {




    [System.ServiceModel.ServiceContractAttribute(Namespace="Bloomberg", ConfigurationName="IStockQuoteService")]
    public interface IStockQuoteService {

        [System.ServiceModel.OperationContractAttribute(Action="GetStockQuote", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/IStockQuoteService/GetStockQuoteResponse")]
        StockQuote GetStockQuote(string request);

        [System.ServiceModel.OperationContractAttribute(Action="GetStockQuote", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/IStockQuoteService/GetStockQuoteResponse", AsyncPattern=true)]
        System.IAsyncResult BeginGetStockQuote(string request, System.AsyncCallback asyncCallback, object userState);

        StockQuote EndGetStockQuote(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action="GetWorldMajorIndices", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/IStockQuoteService/GetWorldMajorIndicesResponse")]
        StockQuote[] GetWorldMajorIndices();

        [System.ServiceModel.OperationContractAttribute(Action="GetWorldMajorIndices", ReplyAction="http://www.restfulwebservices.net/ServiceContracts/2008/01/IStockQuoteService/GetWorldMajorIndicesResponse", AsyncPattern=true)]
        System.IAsyncResult BeginGetWorldMajorIndices(System.AsyncCallback asyncCallback, object userState);

        StockQuote[] EndGetWorldMajorIndices(System.IAsyncResult result);
    }

    public interface IStockQuoteServiceChannel : IStockQuoteService, System.ServiceModel.IClientChannel {
    }

    public class StockQuoteServiceClient : System.ServiceModel.ClientBase<IStockQuoteService>, IStockQuoteService {

        public StockQuoteServiceClient() {
        }

        public StockQuoteServiceClient(string endpointConfigurationName) : 
        base(endpointConfigurationName) {
        }

        public StockQuoteServiceClient(string endpointConfigurationName, string remoteAddress) : 
        base(endpointConfigurationName, remoteAddress) {
        }

        public StockQuoteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
        base(endpointConfigurationName, remoteAddress) {
        }

        public StockQuoteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
        base(binding, endpoint) {
        }

        public StockQuote GetStockQuote(string request) {
            return base.Channel.GetStockQuote(request);
        }

        public System.IAsyncResult BeginGetStockQuote(string request, System.AsyncCallback asyncCallback, object userState) {
            return base.Channel.BeginGetStockQuote(request, asyncCallback, userState);
        }

        public StockQuote EndGetStockQuote(System.IAsyncResult result) {
            return base.Channel.EndGetStockQuote(result);
        }

        public StockQuote[] GetWorldMajorIndices() {
            return base.Channel.GetWorldMajorIndices();
        }

        public System.IAsyncResult BeginGetWorldMajorIndices(System.AsyncCallback asyncCallback, object userState) {
            return base.Channel.BeginGetWorldMajorIndices(asyncCallback, userState);
        }

        public StockQuote[] EndGetWorldMajorIndices(System.IAsyncResult result) {
            return base.Channel.EndGetWorldMajorIndices(result);
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockQuote", Namespace="http://www.restfulwebservices.net/DataContracts/2008/01")]
    public partial class StockQuote : System.Runtime.Serialization.IExtensibleDataObject {

        private string SymbolField;

        private string LastField;

        private string DateField;

        private string TimeField;

        private string ChangeField;

        private string OpenField;

        private string HighField;

        private string LowField;

        private string VolumeField;

        private string MktCapField;

        private string PreviousCloseField;

        private string PercentageChangeField;

        private string AnnRangeField;

        private string EarnsField;

        private string PEField;

        private string NameField;

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                this.SymbolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Last {
            get {
                return this.LastField;
            }
            set {
                this.LastField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Date {
            get {
                return this.DateField;
            }
            set {
                this.DateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Time {
            get {
                return this.TimeField;
            }
            set {
                this.TimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Change {
            get {
                return this.ChangeField;
            }
            set {
                this.ChangeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Open {
            get {
                return this.OpenField;
            }
            set {
                this.OpenField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string High {
            get {
                return this.HighField;
            }
            set {
                this.HighField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Low {
            get {
                return this.LowField;
            }
            set {
                this.LowField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Volume {
            get {
                return this.VolumeField;
            }
            set {
                this.VolumeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string MktCap {
            get {
                return this.MktCapField;
            }
            set {
                this.MktCapField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string PreviousClose {
            get {
                return this.PreviousCloseField;
            }
            set {
                this.PreviousCloseField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string PercentageChange {
            get {
                return this.PercentageChangeField;
            }
            set {
                this.PercentageChangeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string AnnRange {
            get {
                return this.AnnRangeField;
            }
            set {
                this.AnnRangeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Earns {
            get {
                return this.EarnsField;
            }
            set {
                this.EarnsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string PE {
            get {
                return this.PEField;
            }
            set {
                this.PEField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
    }

}
*/